# Generated by Django 3.1.13 on 2021-08-12 09:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=201, null=True)),
                ('description', models.CharField(max_length=201, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('method', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('service_size', models.IntegerField(blank=True, null=True)),
                ('cooking_time', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fibre', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carbohidrates', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('salt', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cooking_level', models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('DIFFICULT', 'DIFFICULT')], max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
