# Generated by Django 3.1.13 on 2021-08-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/uploads/'),
        ),
    ]
