# Generated by Django 3.1.13 on 2021-08-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepes', '0002_auto_20210812_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepes',
            name='calories',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
        migrations.AlterField(
            model_name='recepes',
            name='carbohidrates',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
        migrations.AlterField(
            model_name='recepes',
            name='cooking_level',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('DIFFICULT', 'DIFFICULT')], max_length=201),
        ),
        migrations.AlterField(
            model_name='recepes',
            name='fat',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
        migrations.AlterField(
            model_name='recepes',
            name='fibre',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
        migrations.AlterField(
            model_name='recepes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='recepes',
            name='protein',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
        migrations.AlterField(
            model_name='recepes',
            name='salt',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
    ]
