# Generated by Django 3.1.13 on 2021-08-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepes', '0007_auto_20210823_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepes',
            name='cooking_level',
        ),
        migrations.AlterField(
            model_name='recepes',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
